### ISSUE TITLE
Gulp serve loops endlessly

### ISSUE THREAD

**Issue by mware** [BillyPurvis/jekyll-boilerplate#2]
Hello Billy,
this looked very promising but when I run gulp, the build process loops, constantly autogenerating. Have you encountered this? or found a workaround?

Thx for sharing this.

**Comment by BillyPurvis** [comment]
Hi Michael, 

Thanks for taking a look - I've not worked on this project for a long while, but I am aware of the constant autogenerating - I do remember fixing at one point on my sites using it. I'll see if I can integrate the fix sometime today, or tomorrow.

**Comment by BillyPurvis** [comment]
Hi Micheal, 

I've taken a look - the issue is with the HTML rebuild on the watch task. Since building there's been quite a few changes with gulp and Jekyll. I've decided to cease further fixes for this project as I'm sure there are plenty newer projects out there. Updating this project wouldn't be best for developer or project. 

Really appreciate your interest however, good luck developing with Jekyll in the future!
