### ISSUE TITLE
Using with an existing Jekyll project

### ISSUE THREAD

**Issue by mware** [BillyPurvis/jekyll-boilerplate#3]
I've brought in package.json, the gulp file and adjusted my _config.yml files, run npm install and saw the site at localhost:4000. Hurray!
But on closer examination, autoprefixer did not run, nor did gulp serve regenerate new html that is normally handled by jekyll build.

Can this boilerplate be adapted to an existing project?
Thanks.

**Comment by BillyPurvis** [comment]
Hi Michael, 

I'll take a look into that too - It possibly could, but this was created in an early Jekyll build, so I've not followed since and couldn't promise compatibility for newer Jeykll releases.

**Comment by BillyPurvis** [comment]
Hi Micheal,

I've taken a look - Since building there's been quite a few changes with gulp and Jekyll. I've decided to cease further fixes for this project as I'm sure there are plenty newer projects out there. Updating this project wouldn't be best for developer or project.

Really appreciate your interest however, good luck developing with Jekyll in the future!
